Feature/cp 3452/deleting note
nf2000/nims-notes-things pull request #14
Opened 2022-03-14 13:12 UTC by nf2000

Deleting a note 

https://chillibean.atlassian.net/browse/CP-3454

2022-03-14 14:29 UTC, damonspencerroberts requested changes
Couple of comment but coming along well

2022-03-14 14:29 UTC, damonspencerroberts commented on nims-notes-things/src/components/notes.js
> +          <NavLink to={`/deleteNote/${note.id}`}></NavLink>
Do you need to wrap the delete button around the nav link?

2022-03-14 14:29 UTC, damonspencerroberts commented on nims-notes-things/src/redux/reducers/noteReducer.js
> +        if (note.id === action.id) {
```
if (note.id === action.id) {
          return false;
        }
        return true;
```
can turn into
```
return note.id !== action.id
```

2022-03-14 14:29 UTC, damonspencerroberts commented on nims-notes-things/src/components/Form.js
> +        {!noteId ? (
switch these:
`{noteId ? Update : Submit}`

2022-03-14 14:29 UTC, damonspencerroberts commented on nims-notes-things/src/components/Form.js
> +        {!noteId ? (
easier to read

2022-03-14 14:34 UTC, nf2000 commented on nims-notes-things/src/components/notes.js
> +          <NavLink to={`/deleteNote/${note.id}`}></NavLink>
i don't need the navlink there anymore -> removed it :)

2022-03-15 09:29 UTC, damonspencerroberts approved these changes

2022-03-15 09:49 UTC, merged