Feature/cp 3415/call back logic with validation
nf2000/nims-notes-things pull request #7
Opened 2022-02-23 11:51 UTC by nf2000

Call back Logic

https://chillibean.atlassian.net/browse/CP-3415

2022-02-23 16:04 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +  const validateSubmit = (event) => {
See my comment here for an approach to this issue: https://github.com/alexholmes99/notepadchallenge/pull/6#discussion_r813051361

2022-02-23 16:07 UTC, damonspencerroberts requested changes
More change see my comment for validation on Alex's PR, link above

Also, see me tomorrow regarding file structure.

2022-02-23 16:07 UTC, damonspencerroberts commented on nims-notes-things/src/Button.js
> +  border-radius: 5000px;
why 5000 px for the border-radius?

2022-02-23 16:07 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
>    };
add spaces between functions

2022-02-23 16:07 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +    console.log(empty);
remove console

2022-02-24 14:21 UTC, nf2000 commented on nims-notes-things/src/Button.js
> +  border-radius: 5000px;
this was just a random number to make button edges rounded

2022-02-24 15:39 UTC, damonspencerroberts requested changes
Couple of small comments :)

2022-02-24 15:39 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +        return (isValidated = false);
no need for brackets on the return statement here

2022-02-24 15:39 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +        return (isValidated = true);
no need for an else block

2022-02-24 15:39 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +  const validateSubmit = (event) => {
no need for event argument here if you're not using it

2022-02-24 15:39 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +    const isValidated = validateSubmit(event);
no need to pass the event parameter in `validateSubmit`

2022-02-24 15:53 UTC, damonspencerroberts commented on nims-notes-things/src/Form.js
> +    Object.keys(formData).forEach((data) => {
rename `data` here to `key`

2022-02-28 10:27 UTC, damonspencerroberts approved these changes
Looks good :) Can merge this to main, and then update redux branch with the main branch...

2022-02-28 10:27 UTC, merged